name: Expo EAS Build - Android

on:
  workflow_dispatch:
    inputs:
      build_profile:
        description: 'Seleziona il profilo di build (preview o production)'
        required: true
        default: 'preview'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Verify Expo Login
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas whoami || (echo "Expo login failed" && exit 1)

      - name: Run EAS Build (Android APK/AAB)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform android --profile ${{ github.event.inputs.build_profile }} --non-interactive